# netlify.toml

[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["templates/**/"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
